import Link from "next/link"
import { Button } from "@/components/ui/button"

const FEATURES = [
  {
    icon: "🔍",
    title: "Research any topic",
    description:
      "Paste a URL or describe a topic. The AI scrapes, summarises, and extracts key facts automatically.",
  },
  {
    icon: "✍️",
    title: "AI-written scripts",
    description:
      "Claude writes a structured video script — intro, highlights, stats, quotes, and CTA — tailored to your content.",
  },
  {
    icon: "🎙️",
    title: "ElevenLabs narration",
    description:
      "Every scene gets a professional voiceover generated by ElevenLabs, perfectly synced to the video.",
  },
  {
    icon: "▶",
    title: "Live preview",
    description:
      "See your video update in real-time as the AI generates each scene. No waiting for a full render.",
  },
  {
    icon: "✏️",
    title: "Iterative editing",
    description:
      'Chat to refine any scene. "Make the intro punchier" or "Change the colour to blue" — instant updates.',
  },
  {
    icon: "📥",
    title: "Export & download",
    description:
      "Render a full MP4 with audio baked in. Download it or share it directly from the platform.",
  },
]

export default function HomePage() {
  return (
    <div className="min-h-screen bg-neutral-950 text-white">
      {/* Nav */}
      <nav className="border-b border-neutral-800 px-6 py-4">
        <div className="mx-auto max-w-5xl flex items-center justify-between">
          <span className="text-lg font-bold tracking-tight">opencut</span>
          <div className="flex items-center gap-3">
            <Link
              href="/sign-in"
              className="text-sm text-neutral-400 hover:text-white transition"
            >
              Sign in
            </Link>
            <Link href="/sign-up">
              <Button className="bg-indigo-600 hover:bg-indigo-500 text-white text-sm h-8 px-4">
                Get started
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="mx-auto max-w-3xl px-6 pt-24 pb-16 text-center">
        <div className="inline-flex items-center gap-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-4 py-1.5 text-xs text-indigo-300 mb-8">
          <span className="size-1.5 rounded-full bg-indigo-400 animate-pulse" />
          Built for the ElevenLabs × Firecrawl Hackathon
        </div>

        <h1 className="text-5xl font-bold tracking-tight leading-[1.1] mb-6">
          Generate stunning videos{" "}
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400">
            with AI
          </span>
        </h1>

        <p className="text-lg text-neutral-400 leading-relaxed mb-10 max-w-xl mx-auto">
          Describe a topic or paste a URL. Opencut researches, scripts, narrates,
          and produces a fully-edited video — in under a minute.
        </p>

        <div className="flex items-center justify-center gap-4">
          <Link href="/sign-up">
            <Button className="bg-indigo-600 hover:bg-indigo-500 text-white h-11 px-7 text-base">
              Start for free
            </Button>
          </Link>
          <Link href="/dashboard">
            <Button
              variant="outline"
              className="border-neutral-700 text-neutral-300 hover:text-white hover:border-neutral-500 h-11 px-7 text-base"
            >
              Go to dashboard →
            </Button>
          </Link>
        </div>
      </section>

      {/* Demo strip */}
      <section className="border-y border-neutral-800 bg-neutral-900/40 py-8 overflow-hidden">
        <div className="mx-auto max-w-5xl px-6">
          <div className="flex items-center gap-3 rounded-xl border border-neutral-700 bg-neutral-900 p-4 text-sm text-neutral-400">
            <span className="size-2.5 rounded-full bg-emerald-400 shrink-0 animate-pulse" />
            <span className="font-mono text-xs text-neutral-500">AI:</span>
            <span className="truncate">
              Researching "The Future of AI"… writing script… generating 6
              scenes with narration… video ready in 42s ✓
            </span>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-5xl px-6 py-20">
        <h2 className="text-2xl font-semibold text-center mb-12">
          Everything you need to create videos with AI
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {FEATURES.map((f) => (
            <div
              key={f.title}
              className="rounded-xl border border-neutral-800 bg-neutral-900 p-5 space-y-2.5"
            >
              <span className="text-2xl">{f.icon}</span>
              <h3 className="text-sm font-semibold text-white">{f.title}</h3>
              <p className="text-xs text-neutral-500 leading-relaxed">
                {f.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-neutral-800 py-20 text-center px-6">
        <h2 className="text-3xl font-bold mb-4">Ready to create?</h2>
        <p className="text-neutral-500 mb-8 text-sm">
          Free to start. No credit card required.
        </p>
        <Link href="/sign-up">
          <Button className="bg-indigo-600 hover:bg-indigo-500 text-white h-11 px-8 text-base">
            Create your first video →
          </Button>
        </Link>
      </section>

      <footer className="border-t border-neutral-800 py-6 px-6 text-center text-xs text-neutral-600">
        © {new Date().getFullYear()} Opencut — AI Video Generator
      </footer>
    </div>
  )
}
